package com.drp.shared_ui.naviagtion

sealed class Screens(val route: String) {
    data object LandingPageScreen : Screens(route = LandingPageScreen::class.java.name)
    data object ShahkarLoginScreen : Screens(route = ShahkarLoginScreen::class.java.name)
    data object BillInquiryScreen : Screens(route = BillInquiryScreen::class.java.name)
    data object SeparatedBillInquiryScreen : Screens(route = SeparatedBillInquiryScreen::class.java.name)
    data object SettingScreen : Screens(route = SettingScreen::class.java.name)
    data object AuthenticationScreen : Screens(route = AuthenticationScreen::class.java.name)
    data object BalanceScreen : Screens(route = BalanceScreen::class.java.name)
    data object LastTenStatementScreen : Screens(route = LastTenStatementScreen::class.java.name)
    data object LastTenStatementResultScreen : Screens(route = LastTenStatementResultScreen::class.java.name)
    data object TopUpScreen : Screens(route = TopUpScreen::class.java.name)
    data object CardToCardScreen: Screens(route = CardToCardScreen::class.java.name)
    data object InternetPackageInquiryScreen : Screens(route = InternetPackageInquiryScreen::class.java.name)
    data object InternetPackageTypeScreen : Screens(route = InternetPackageTypeScreen::class.java.name)
    data object WebPageScreen : Screens(route = WebPageScreen::class.java.name)
    data object InstallmentInquiryScreen : Screens(route = InstallmentInquiryScreen::class.java.name)
    data object TransactionHistoryScreen : Screens(route = TransactionHistoryScreen::class.java.name)
    data object HistoryScreen : Screens(route = HistoryScreen::class.java.name)
    data object InsuranceInquiryScreen : Screens(route = InsuranceInquiryScreen::class.java.name)
    data object WalletAddScreen : Screens(route = WalletAddScreen::class.java.name)
    data object WalletMinusScreen : Screens(route = WalletMinusScreen::class.java.name)
    data object WalletToWalletScreen : Screens(route = WalletToWalletScreen::class.java.name)
    data object CameraScreen: Screens(route = CameraScreen::class.java.name)
    data object LicenceNegativeScoreInquiryScreen: Screens(route = LicenceNegativeScoreInquiryScreen::class.java.name)
    data object TrackingPostScreen: Screens(route = TrackingPostScreen::class.java.name)
    data object IbanConvertorScreen: Screens(route = IbanConvertorScreen::class.java.name)
    data object VehicleViolationScreen: Screens(route = VehicleViolationScreen::class.java.name)
    data object MotorViolationScreen: Screens(route = MotorViolationScreen::class.java.name)
}
