package com.drp.utils

const val CONTACTLIST: String = "contact"
const val REQUEST: String = "request"
const val TITLE: String = "title"
const val ITEMS: String = "items"
const val TYPE: String = "type"
const val RESULT: String = "result"
const val RECEIPTTITLE: String = "receiptTitle"
const val RECEIPTMODE: String = "receiptMode"
const val COMPOSE_RECEIPT: String = "composeMode"
const val IMAGE: String = "image"
const val PICHACK: String = "pickack"
const val CHEQUE_SUBMIT_RECEIPT = "cheque_submit_receipt"
const val HISTORYRECEIPT: String = "history_Receipt"
const val SHOW_EDIT_MODE: String = "showEditMode"
const val TITLE_SHEET: String = "title_sheet"
const val TIMER = 121
const val SELECTED_CARD_KEY = "selected_card"

const val P_WALLET = "P_WALLET"
const val P_WALLET_ID = "P_WALLETID"
const val P_PAYMENTTYPE = "P_PAYMENTTYPE"
const val P_AMOUNT = "P_AMOUNT"
const val P_FROMIBAN = "P_FROMIBAN"
const val P_SRC_CARD_NO = "P_SRC_CARD_NO"
const val P_SRC_CARD_CVV2 = "P_SRC_CARD_CVV2"
const val P_SRC_CARD_EXP_YEAR = "P_SRC_CARD_EXP_YEAR"
const val P_SRC_CARD_EXP_MONTH = "P_SRC_CARD_EXP_MONTH"
const val P_DST_CARD_NO = "P_DST_CARD_NO"
const val P_TOIBAN = "P_TOIBAN"
const val P_SEND_OTP_SMS = "P_SEND_OTP_SMS"
const val P_DESCRIPTION = "P_DESCRIPTION"
const val P_ACTORPERSONID = "P_ACTORPERSONID"
const val P_REFCODE = "P_REFCODE"
const val P_MOBILE = "P_MOBILE"
const val P_POSTCALL_URL = "P_POSTCALL_URL"
const val P_POSTCALL_METHOD = "P_POSTCALL_METHOD"
const val P_POSTCALL_BODY = "P_POSTCALL_BODY"
const val P_RQID = "P_RQID"
const val P_PIN = "P_PIN"


const val P_FROMWALLET = "P_FROMWALLET"
const val P_TOWALLET = "P_TOWALLET"
const val P_DEBIT_DESCRIPTION = "P_DEBIT_DESCRIPTION"
const val P_DEBIT_FEEAMOUNT = "P_DEBIT_FEEAMOUNT"
const val P_CREDIT_DESCRIPTION = "P_CREDIT_DESCRIPTION"
const val P_CREDIT_FEEAMOUNT = "P_CREDIT_FEEAMOUNT"
const val P_BABATID = "P_BABATID"
const val P_FROMMOBILE = "P_FROMMOBILE"
const val P_TOMOBILE = "P_TOMOBILE"


const val EXECUTER_CALL_TYPE = "Executer"
const val ASCII_ENCODING = "ASCII"
const val REQUEST_ID = "RequestID"

