package com.drp.data.enums

enum class CardOtpRequestType(val dynPinRequestType: Int? = null) {
    PAYMENT,
    FUND_TRANSFER,
    FUND_TRANSFER_TO_ACCOUNT,
    GET_BALANCE(2),
    BILL_PAYMENT,
    MINI_STATEMENT(4),
    AUTHENTICATION_TOPUP_PAYMENT,
    AUTHENTICATION_LOAN_PAYMENT,
    AUTHENTICATION_PACKAGE_PAYMENT,
    AUTHENTICATION,
    CARD_LESS_ADD,
    CARD_LESS_CANCEL,
    MODIFY_CARD_FIRST_PASS
}